POST  http://192.168.99.61/grafana/api/dashboards/db HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJrIjoiNjlMQ3hMMGFlOWJnNzBCTTE3ejZtN1BUSmRSeGlBTXYiLCJuIjoiYXV0by1rZXkiLCJpZCI6MX0=

{
    "dashboard":{
    "id" : "8",
    "uid": "MQiLpbXGz",
    "panels" : [{
        "id" : 11,
        "title" : "yo"
        
    }],
    "title" : "Update via api",
    "version" : 16
    
    
    }
}

####
GET /api/search?starred=true HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJrIjoiNjlMQ3hMMGFlOWJnNzBCTTE3ejZtN1BUSmRSeGlBTXYiLCJuIjoiYXV0by1rZXkiLCJpZCI6MX0=

